# Generated by Django 4.2 on 2023-04-16 02:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_rename_id_move_room_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='move',
            old_name='room_id',
            new_name='room',
        ),
    ]
