# Generated by Django 4.2 on 2023-04-16 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_room_status_alter_room_turn_alter_room_user1_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='board',
            name='cells',
        ),
        migrations.RemoveField(
            model_name='board',
            name='size',
        ),
        migrations.AlterField(
            model_name='room',
            name='status',
            field=models.CharField(default='waiting', max_length=20),
        ),
    ]
