# Generated by Django 4.2 on 2023-04-16 05:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_remove_board_cells_remove_board_size_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='board',
            name='id',
        ),
        migrations.AddField(
            model_name='board',
            name='board',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='board',
            name='room',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='accounts.room'),
        ),
    ]
