# Generated by Django 4.2 on 2023-04-18 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_remove_board_id_board_board_alter_board_room'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='name_user1',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='room',
            name='name_user2',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
