# Generated by Django 4.2 on 2023-04-18 16:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_room_name_user1_room_name_user2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='name_user1',
        ),
        migrations.RemoveField(
            model_name='room',
            name='name_user2',
        ),
    ]
